//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string movieyear { get; set; }
        public string director { get; set; }
    }
}
